### PR TITLE
feat(mount): copy {script,link} tags

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Allows us to create root views that look like:
```js

function mainView (state, prev, send) {
  return html`
    <body>
      <main>
        <h1 class="f-6">choo choo</h1>
      </main>
    </body>
  `
}
```
And these will have like all the `<script>` and `<link>` tags copied over, without triggering again and other weird stuff :ok_hand:

### CODE REVIEW

**Comment by timwis** [comment]
Hm, I've never seen a `<link>` tag in the `<body>`, only in the `<head>`. Maybe that tag's not necessary to check?

Would you still initiate choo via `const tree = app.start(); document.body.appendChild(tree)` ?

**Comment by ungoldman** [comment]
why not `<html>`? :trollface:

**Comment by yoshuawuyts** [comment]
lol, go away 👻

**Comment by yoshuawuyts** [comment]
ok turns out some of my replies haven't come through. @timwis I replied:
> Haha, oops - yeah you're right :D

> Yeah nah, in this case you couldn't do that - appending body to body wouldn't work.
Right now `mount()` is being used for server side rendering, but it could be used
to replace any type of node - in this case we're going for the body, which I guess is
also already rendered on the server so it kinda fits in that line hah

Second email:
> Updated PR :sparkles:

**Comment by yoshuawuyts** [comment]
margin!

**Comment by yoshuawuyts** [comment]
lol, go away 👻

**Comment by yoshuawuyts** [comment]
Updated PR :sparkles:

**Comment by ungoldman** [comment]
hmm weird, looks like those email responses finally came through! I responded to another issue over email this morning and didn't see it show up. betting @github's message queue is borked somewhere

**Comment by yoshuawuyts** [comment]
yeah super odd

**Comment by yoshuawuyts** [comment]
Haha, oops - yeah you're right :D

Yeah nah, in this case you couldn't do that - appending body to body
wouldn't work.
Right now `mount()` is being used for server side rendering, but it could
be used
to replace any type of node - in this case we're going for the body, which
I guess is
also already rendered on the server so it kinda fits in that line hah

**Comment by ungoldman** [comment]
👻  ghost in the machine

**Pull request merged**
