### PR TITLE
remove default route, parse qs

### PR DESCRIPTION
**Pull request by yoshuawuyts**
- removes the default route in favor of `'*'` (as per @timwis sugestion)
- documents the router
- add queryString parsing under `state.query`

### CODE REVIEW

**Comment by timwis** [comment]
Woo! Should we mention that the wildcard should be the last route do it doesn't get triggered early?

**Comment by yoshuawuyts** [comment]
> the wildcard should be the last route do it doesn't get triggered early?

Errr, does it? I believe you implemented it on the router, but with a trie structure the order of declaration shouldn't matter - if it does, it sounds like a bug on the router :/

**Comment by yoshuawuyts** [comment]
Related to https://github.com/yoshuawuyts/choo/issues/519

**Comment by yoshuawuyts** [comment]
Yeah, just verified in `wayfarer` that order indeed doesn't matter

**Comment by yoshuawuyts** [comment]
Yeah it's b/c pelo needs to be updated - merging!

**Comment by yoshuawuyts** [comment]
:package: `v6.0.0-1` - `npm i choo@next`

**Pull request merged**
