### PR TITLE
Add IRC badge

### PR DESCRIPTION
**Pull request by timwis**
Unless there's somewhere else it's advertised?

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
:fire: It's not a square! :fire:

haha, other than that I'm +1 (':

**Comment by timwis** [comment]
hah! my bad, fixed

**Comment by yoshuawuyts** [comment]
haha, merge commits? 😛

**Comment by timwis** [comment]
:O so much power

**Comment by yoshuawuyts** [comment]
haha, I meant: "could you merge the commits into one commit" - but this is fine :grin: - someday I'll write a commit linter to make everyone adhere to my commit style. Until then... ah well, who cares

**Comment by timwis** [comment]
oh! haha my bad, should have done an `--amend`

**Pull request merged**
